export const {
  KAFKA_BROKER_LIST = "kafka-1:9094",
  ENDPOINT_PRODUCER_ID = "endpoint-producerv1",
  ENDPOINT_CONSUMER_ID = "endpoint-consumerv1",
  ENDPOINT_CONSUMER_GROUP_ID = "endpointv8",
  //TOPIC----
  ENDPOINT_CONSUMER_TOPIC = "SOCKET",
  ENDPOINT_PRODUCER_TOPIC = "SESSION",

  TASK_MAX_ATTEMPT = "3",
  ENCRYPTION_KEY = "bf3c199c2470cb477d907b1e0917c17b",
  ENCRYPTION_IV = "5183666c72eec9e4",
  ENDPOINT_METADATA_MAX_AGE = "300000",
  ENDPOINT_AUTO_TOPIC_CREATION = "true",
  ENDPOINT_TRANSACTION_TIMEOUT = "60000",

  //SOCKET
  SOCKET_PORT = "3001",
} = process.env;
